name: Kubescape scanning for misconfigurations
on: [push, pull_request]
jobs:
  kubescape-scan:
    permissions:
      contents: write
      pull-requests: write
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: kubescape/github-action@main
      continue-on-error: true
      with:
        frameworks: AllControls
        format: sarif
        outputFile: results.sarif
    - name: Upload Kubescape scan results to Github Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
